---
fdio:
    general:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        image_properties: {'hw_mem_page_size':'large'}
        openstack:
            flavor_ram: 1024
    snaps:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
    vmready1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vmready2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    singlevm1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    singlevm2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vping_ssh:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vping_userdata:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    cinder_test:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_smoke:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    neutron-tempest-plugin-api:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    refstack_defcore:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    patrole:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vmtp:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 2048
    shaker:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    neutron_trunk:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    networking-bgpvpn:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    networking-sfc:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    barbican:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_full:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_scenario:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_sanity:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_full:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    cloudify:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    cloudify_ims:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    heat_ims:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    vyos_vrouter:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    juju_epc:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}

ovs:
    general:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        image_properties: {'hw_mem_page_size':'large'}
        openstack:
            flavor_ram: 1024
    snaps:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
    vmready1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vmready2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    singlevm1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    singlevm2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vping_ssh:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vping_userdata:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    cinder_test:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_smoke:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    neutron-tempest-plugin-api:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    refstack_defcore:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    patrole:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vmtp:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 2048
    shaker:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    neutron_trunk:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    networking-bgpvpn:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    networking-sfc:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    barbican:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_full:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_scenario:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_sanity:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_full:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    cloudify:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    cloudify_ims:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    heat_ims:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    vyos_vrouter:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    juju_epc:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
